services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_USER_MANAGEMENT_DISABLED=true
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network

  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5001"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PROMPT=${PROMPT}
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - ./videos:/app/videos
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
